[[actions]]
name = "play"
platform = "windows"
path = "FairytaleMod_Clangen/FairytaleMod.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "FairytaleMod_Clangen/FairytaleMod"
args = ["--launched-through-itch"]
